import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/Components/Shared/Navbar/Navbar';
import Footer from '@/Components/Shared/Footer/Footer';
import AuthProvider from '@/Providers/AuthProvider';


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" data-theme="light">
      <AuthProvider>
        <body className={inter.className}>
          <Navbar />
          {children}

          <Footer></Footer>
        </body>
      </AuthProvider>
    </html>
  )
}
